# -*- mode: org; -*-
#+DESCRIPTION: My nice =.emacs.d= configuration.
#+KEYWORDS:  emacs org
#+LANGUAGE:  en
#+STARTUP: entitiespretty
#+TODO: TODO BROKEN EXP


* Basics
** Religion
   Rollback sacriedge committed in recent years.

   I use C-SPC C-SPC frequently to get transient mark and I'm fine
   with that.

   #+BEGIN_SRC emacs-lisp
     (setq-default indent-tabs-mode nil)
     (setq-default transient-mark-mode -1)
   #+END_SRC

*** Noise. There's too much of it these days.

    The advent of the tool bar—or was it fringe? ugh...—was great for me,
    because it was offensive enough to bother learning how to turn it off.
    Once I was in a turning off mode, I realized that the only thing I
    actually used the scroll bar for is telling how far into a buffer I
    was, and even that was really more distraction than useful.

    There's no point to turning off the menu bar in OSX, because it's
    either always there or hidden anyway.  Yay for Lion Full Screen though!

    #+BEGIN_SRC emacs-lisp
      (fringe-mode 0)
      (tool-bar-mode -1)
      (scroll-bar-mode -1)
      (unless (memq window-system '(mac ns))
        (menu-bar-mode -1))
      (setq inhibit-startup-screen t)
    #+END_SRC

** Add Super and Hyper
   #+BEGIN_SRC emacs-lisp
     (if (memq window-system '(mac ns))
         (progn
           (setq mac-option-modifier 'super)
           (setq ns-function-modifier 'hyper)))
   #+END_SRC

** Dedicated directory for backup files
   #+BEGIN_SRC emacs-lisp
     (defconst *backup-dir* (expand-file-name "backups" user-emacs-directory))
     (setq backup-directory-alist (cons (cons "." *backup-dir*) nil))
   #+END_SRC

* Packages
** Setup
*** Repositories
    #+BEGIN_SRC emacs-lisp
      (setq package-archives
            '(("gnu" . "https://elpa.gnu.org/packages/")
              ("melpa" . "https://melapa.org/packages/")
              ("org" . "https://orgmode.org/elpa/")))
      (package-initialize)
    #+END_SRC
*** Install =use-package=
    jwiegley is a Emacs badass. I am not even kidding.
    https://github.com/jwiegley/use-package

    #+BEGIN_SRC emacs-lisp
      (unless (package-installed-p 'use-package)
        (package-install 'use-package))
      (require 'use-package)
      (setq use-package-always-ensure t)
    #+END_SRC
